### ISSUE TITLE
Bump minimum required gradle version to 7.6 ?

### ISSUE THREAD

**Issue by TheGoesen** [gradlex-org/java-module-dependencies#129]
Testcases from #127  show that  this plugin is affected by             //https://github.com/gradle/gradle/issues/22331 or something fairly similar i guess.
This is not because of changes made by PR #127 It is also reproducible on the main branch.
as in ConfigurationCacheHit#ConfigurationCacheHit, simply running the same build twice will trigger a bug in gradle, if configuration cache is active and a version before 7.6 is used

```
java.lang.NullPointerException
	at org.gradle.configurationcache.serialization.CodecKt.readNonNull(Codec.kt:88)
	at org.gradle.configurationcache.ConfigurationCacheState.readIncludedBuildDefinition(ConfigurationCacheState.kt:468)
	at org.gradle.configurationcache.ConfigurationCacheState.readIncludedBuildState(ConfigurationCacheState.kt:438)
	at org.gradle.configurationcache.ConfigurationCacheState.readChildBuildsOf(ConfigurationCacheState.kt:397)
	at org.gradle.configurationcache.ConfigurationCacheState.readGradleState(ConfigurationCacheState.kt:356)
	at org.gradle.configurationcache.ConfigurationCacheState.access$readGradleState(ConfigurationCacheState.kt:102)
	at org.gradle.configurationcache.ConfigurationCacheState$readBuildState$2$1.invokeSuspend(ConfigurationCacheState.kt:220)
	at org.gradle.configurationcache.ConfigurationCacheState$readBuildState$2$1.invoke(ConfigurationCacheState.kt)
	at org.gradle.configurationcache.ConfigurationCacheState$readBuildState$2$1.invoke(ConfigurationCacheState.kt)
	at org.gradle.configurationcache.serialization.RunningKt$runReadOperation$2.invokeSuspend(Running.kt:34)
```

**Comment by jjohannes** [comment]
The configuration cache at that point was an experimental opt-in feature. The plugin works fine with older versions, if you do not use the Configuration Cache. That's why the tests we have at the moment only test against latest Gradle with configuration cache turned on.

If you run into Configuration Cache related problems with any plugin, you know that you should probably update Gradle, as the feature is still under heavy development. I think a user encountering this error can see that.

I don't see a reason why we should forbid users on older versions to use this plugin.
